name: Sample

on:
  push:
    branches:
      - main

env:
  DOCKER_REGISTRY: docker.io/akashkam/podman
  DOCKER_USERNAME: akashkam


jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to Docker registry by Podman
      run: |
        podman login  "${{ env.DOCKER_REGISTRY }}" -u "${{ env.DOCKER_USERNAME }}" -p ${{ secrets.DOCKER_PASSWORD }}

    - name: Voting Application Build Image using podman
      run: |
        sudo podman build -t vote:v1 vote/.
        sudo podman push vote:v1
        
    - name: Result Application Build Image using podman
      run: |
        sudo podman build -t result:${{ env.IMAGE_TAG }} result/.
        sudo podman push result:${{ env.IMAGE_TAG }}
  
    - name: Worker Application Build Image using podman
      run: |
        sudo podman build -t worker:${{ env.IMAGE_TAG }} worker/.
        sudo podman push worker:${{ env.IMAGE_TAG }}
