name: Build and Push Docker Image with Podman

on:
  push:
    branches:
      - main

env:
  DOCKER_REGISTRY: docker.io
  DOCKER_USERNAME: akashkam
  DOCKER_REPOSITORY: akashkam/podman
  COMMIT_SHA: ${{ github.sha }}

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to Docker registry by Podman
      run: |
        podman login  "${{ env.DOCKER_REGISTRY }}" -u "${{ env.DOCKER_USERNAME }}" -p ${{ secrets.DOCKER_PASSWORD }}


    - name: Voting Application Build Image using podman
      run: |
        cd vote/
        podman build -t ${{ env.DOCKER_REPOSITORY }}:${{ COMMIT_SHA }} .
        podman push ${{ env.DOCKER_REPOSITORY }}:${{ COMMIT_SHA }}
        
    - name: Result Application Build Image Using Podman
      run: |
        cd result/
        podman build -t ${{ env.DOCKER_REPOSITORY }}:${{ COMMIT_SHA }} .
        podman push ${{ env.DOCKER_REPOSITORY }}:${{ COMMIT_SHA }}
  

    - name: Worker Application Build Image Using Podman
      run: |
        cd worker/
        podman build -t ${{ env.DOCKER_REPOSITORY }}:${{ COMMIT_SHA }} .
        podman push  ${{ env.DOCKER_REPOSITORY }}:${{ COMMIT_SHA }}
        
#     - name: Connect to AKS Cluster
#       run: |
#         az account set --subscription 95dc6442-7e4b-48c8-8960-9e89c991c067
#         az aks get-credentials --resource-group RG-Containerization2 --name akscluster-002
#         kubectl get pods
        
