name: Build and Push Docker Image with Podman

on:
  push:
    branches:
      - main

env:
  DOCKER_REGISTRY: docker.io
  DOCKER_USERNAME: akashkam
  DOCKER_REPOSITORY: akashkam/podman

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to Docker registry by Podman
      run: |
        podman login  "${{ env.DOCKER_REGISTRY }}" -u "${{ env.DOCKER_USERNAME }}" --p Kamble@22


    - name: Voting Application Build Image Using Podman
      run: |
        cd vote/
        podman build -t ${{ env.DOCKER_REGISTRY }}/vote:v3 .
        podman push ${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_REPOSITORY }}:v3
        
    - name: Result Application Build Image Using Podman
      run: |
        cd result/
        podman build -t ${{ env.DOCKER_REGISTRY }}/result:r3 .
        podman push ${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_REPOSITORY }}:r3
  

    - name: Worker Application Build Image Using Podman
      run: |
        cd worker/
        podman build -t ${{ env.DOCKER_REGISTRY }}/worker:w3 .
        podman push ${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_REPOSITORY }}:w3
        
