name: Build and Push Docker Image with Podman

on:
  push:
    branches:
      - main

env:
  DOCKER_REGISTRY: docker.io/akashkam/podman
  DOCKER_USERNAME: akashkam
  IMAGE_NAME: myimage
  IMAGE_TAG: ${{ github.run_number }}

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to Docker registry by Podman
      run: |
        podman login  "${{ env.DOCKER_REGISTRY }}" -u "${{ env.DOCKER_USERNAME }}" -p ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker Image with Podman
      run: |
        cd vote/
        podman build -t ${{ env.DOCKER_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} .

    - name: Push Docker Image with Podman
      run: |
        podman push ${{ env.DOCKER_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
